app:
  apiKey: trnsl.1.1.20150904T170427Z.a9fe635412c9f994.e0dafbb5b92d6a794b77144eef59ec2c85c8b450
  baseUrl: https://translate.yandex.net/api/v1.5/tr.json/
  apiKeyQueryParamName: key
  proxySettings:
    http:
      proxyHost: myproxy.com
      proxyPort: 3128
      proxyLogin: http.proxyLogin
      proxyPassword: http.proxyPassword
    https:
      proxyHost: https.proxyHost
      proxyPort: https.proxyPort
      proxyLogin: https.proxyLogin
      proxyPassword: https.proxyPassword

